### ISSUE TITLE
Remove dependency on the arcgis-js-api typings library

### ISSUE THREAD

**Issue by kgs916** [kgs916/angular2-esri4-components#3]

**Comment by kgs916** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Issue #3: Remove dependency on the arcgis-js-api typings library](https://trello.com/c/SgwBpdzq/4-issue-3-remove-dependency-on-the-arcgis-js-api-typings-library)

**Comment by tomwayson** [comment]
@kgs916 - seems like this is related to https://github.com/tomwayson/angular2-esri-loader/issues/2

Just curious, are you planning on using @types for this repo?

**Comment by kgs916** [comment]
@tomwayson - I definitely want to move towards @types.  If I recall correctly I had some issues with using the ESRI library that was on @types before.  It looks like those issues have been figured out over at angular2-esri-loader.  I'll give it another go.
