### ISSUE TITLE
Loading issue for Angular2Esri4Module module

### ISSUE THREAD

**Issue by HuChaoyong** [kgs916/angular2-esri4-components#7]
when I use `ng serve`,it will get an error 
`10%building modules 2/2 modules 0 activeError: Angular2Esri4Module is not an NgModule`,
and then it stuck at 70% 
`70% building modules 695/695 modules 0 active`
but if I put `Angular2Esri4Module` in the `declarations` a moment,
after `ng serve` run,then put `Angular2Esri4Module` back to  `imports`,
it works normally.
How do I change my code ?or it's about package ?
`D:\Angular2\app_test>ng --version`
`angular-cli: 1.0.0-beta.22`
`node: 6.9.2`
`os: win32 x64`
my package.json
`  "@angular/common": "2.2.3",                                                  `
 `   "@angular/compiler": "2.2.3",                                                `
  `  "@angular/core": "2.2.3",                                                       `
   ` "@angular/forms": "2.2.3",                                                     `
    `"@angular/http": "2.2.3",                                                        `
    `"@angular/platform-browser": "2.2.3",                                  `
    `"@angular/platform-browser-dynamic": "2.2.3",                   `
    `"@angular/router": "3.2.3",                                                    `
    `"@ngtools/webpack": "1.1.9",                                                `
    `"angular2-esri4-components": "^0.3.0",                                ` 
    `"core-js": "^2.4.1",                                                                  `
    `"rxjs": "5.0.0-beta.12",                                                             `
    `"ts-helpers": "^1.1.1",                                                             `
    `"zone.js": "^0.6.23"                                                                 `

**Comment by kgs916** [comment]
@HuChaoyong Thanks for raising the issue!  I'll take a look at this on my end and let you know what I find.

**Comment by kgs916** [comment]
@HuChaoyong It appears to me right now that there is something in the angular-cli that is causing this to happen.  I'm continuing to look into better options but what I have for you right now are:

* this issue is not happening [esri-angular-cli-example](https://github.com/tomwayson/esri-angular-cli-example) which is using angular-cli 1.0.0-beta.19-3.  If you downgrade your angular-cli to this version the issues should go away.
* I have tested this on a project using angular-cli 1.0.0-beta.24.  The `ERROR in Angular2Esri4Module is not an NgModule` is still there but the build process completes and everything functions correctly.  Upgrading the angular-cli to this version could put you in a better position.

One of the above options is the best I have at the moment.  There are a number of [issues](https://github.com/angular/angular-cli/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22is%20not%20an%20NgModule%22) open on angular-cli surrounding similar error messages so I will monitor what happens over there. I will be sure to update this thread when I find a better solution.

**Comment by HuChaoyong** [comment]
@kgs916 thanks, now I update `angular-cli` to beta.24 ,situation is that  you said ,
but I find something interesting ,I use 'ng serve ' for my old project which is created by angular-cli beta.22 ,
it doesn't get error ! I don't know what happen.
oh,I find two issues in project, I forget tell you last time.

1.  If I don't import `EsriLoaderService` to` app.module.ts` and put it in `providers`, it will get a error 
`AppComponent - inline template:0:0 caused by: No provider for EsriLoaderService!` on the html.
2. In map.component.ts , If don't give a css class like `.map{ height: 500px;}` for `template`,
template like 
`<div class="map">`
  `  <esri4-map `
   ` [mapProperties]="mapProperties" `
   ` [mapViewProperties]="mapViewProperties" `
  `  (mapInit)="onMapInit($event)">`
    `</esri4-map>`
`</div>`,
the map can't display in the html.(i.e. no error for this )

**Comment by kgs916** [comment]
@HuChaoyong Thanks for giving more feedback.  My responses are below.

1. If all you are doing is loading a map using the `esri4-map` component from the `angular2-esri4-components` package then you should not need to include `EsriLoaderService` as a provider for your module.  You need to include `EsriLoaderService` as a provider in your module if you plan to load any other ESRI modules into your application. `angular2-esri4-components` does not expose this service globally.

2. I'm not sure there is much that I can do about validating the CSS on the template.  However, I did not include any CSS in the examples in the README.  I will go ahead and include some CSS as it sounds like that would be helpful.

**Comment by kgs916** [comment]
@HuChaoyong You mentioned that you have a project that was originally created with beta.22 of the angular-cli and is not getting the error after upgrading the CLI.  Could you provide me with the list of dependencies in the package.json from that project?

**Comment by HuChaoyong** [comment]
@kgs916  I'm sorry about that. I tested my project many times just now, but I found I can't back to that situation.might be I misread at three days ago.I'm really sorry about that.

**Comment by kgs916** [comment]
No problem, @HuChaoyong.  Thanks for trying!

**Comment by kgs916** [comment]
@HuChaoyong I have corrected this issue in v0.4.1 of this library.  It required using the @angular/compiler-cli to transpile the TS rather than using tsc.  I'm going to close this issue now.  Please let me know if you continue to encounter the issue and I can reopen this.

**Comment by HuChaoyong** [comment]
@kgs916 , no problem.
