### ISSUE TITLE
Handle Map Events and Search Widgets

### ISSUE THREAD

**Issue by victorv977** [kgs916/angular2-esri4-components#9]
Hi, I have a couple questions:

1. There is a way to handle maps events? For example I need handle `onExtentChange` event and capture the new coordinates.
2. Is there a way to add Search Widget to the map?

maybe @tomwayson can help with this question.

Thanks!

**Comment by kgs916** [comment]
Hi @victorv977,

As far as I know `onExtentChange` was in ArcGIS API for JavaScript v3 but does not exist in v4.  This library uses v4.  However, there is a [sample](https://developers.arcgis.com/javascript/latest/sample-code/watch-for-changes/index.html) on the ArcGIS website that explains how to watch for an extent change.

The way you might implement that with this library is to provide an `onMapInit` event function to the `esri4-map` component like this:

```
import { Component } from '@angular/core';

import { Esri4MapComponent } from 'angular2-esri4-components';
import { EsriLoaderService } from 'angular2-esri-loader';

@Component({
  selector: 'app-map',
  template: `
    <esri4-map [mapProperties]="mapProperties" [mapViewProperties]="mapViewProperties" (mapInit)="onMapInit($event)"></esri4-map>
  `,
  styleUrls: ['./map.component.scss']
})
export class MapComponent {
  /* ... */
  constructor(private esriLoader: EsriLoaderService) { }

  onMapInit(mapInfo: { map: __esri.Map, mapView: __esri.MapView }) {
    this.mapService.initializeMap(mapInfo.map, mapInfo.mapView);

    let map = mapInfo.map;
    let mapView = mapInfo.mapView;

    this.esriLoader.loadModules([
      'esri/core/watchUtils', 'esri/widgets/Search'
    ]).then(([watchUtils, Search]: [__esri.watchUtils, __esri.SearchConstructor]) => {
      watchUtils.whenTrue(mapView, 'stationary', () => {
        if (mapView.extent) {
          let info = "<br> <span> the view extent changed: </span>" +
            "<br> xmin:" + mapView.extent.xmin.toFixed(2) + " xmax: " +
            mapView.extent.xmax.toFixed(2) +
            "<br> ymin:" + mapView.extent.ymin.toFixed(2) + " ymax: " +
            mapView.extent.ymax.toFixed(2);
          console.log(info);
        }
      });

      // add search widget to map
      const searchWidget = new Search({
        view: mapView
      });
      mapView.ui.add(searchWidget, 'top-right');
    });
  }
}
```

I also threw in the Search widget in this example.  You can find documentation about the Search widget [here](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Search.html).

**Comment by victorv977** [comment]
Thanks @kgs916, its works!
